[book]
authors = ["Alix ANNERAUD"]
language = "en"
multilingual = false
src = "src"
title = "Xila book"
description = "Xila book"


[output.html]
git-repository-url = "https://github.com/Xila-Project"
git-repository-icon = "fa-github"
smart-punctuation = true
mathjax-support = true
copy-fonts = true
cname = "book.xila.dev"